### PR TITLE
chore: add funtoo to install table

### PR DESCRIPTION
**Pull request by invakid404**
Hello 👋🏻,

I maintain the rustcat package over at Funtoo Linux. I've already added Funtoo install steps to the wiki, so I thought I might as well mention how to install rustcat on Funtoo in the README :^)

### CODE REVIEW

**Comment by robiot** [comment]
Looks great except the https://github.com/funtoo/net-kit/tree/1.4-release/net-analyzer/rustcat link is a 404. Is it just not added yet?

**Comment by invakid404** [comment]
It will be there once a tree regen hits production, the link itself is correct :^)

**Comment by robiot** [comment]
:+1:

**Comment by robiot** [comment]
Just a last question. In the wiki you put "emerge net-analyzer/rustcat". But in the readme its just "emerge rustcat".
Which is the correct one?

**Comment by invakid404** [comment]
Both are completely valid, `emerge rustcat` is just more concise. The category (catpkg) is generally optional for emerge. I just decided to be more specific for the wiki. The result is equivalent.

**Pull request merged**
